name: CI
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build source code
        run: |
          npm i
          npm run export
      - name: Generates Sitemap
        run: |
          node .github/scripts/generate-sitemap.js
      - name: Install Firebase Tools
        run: |
          npm i firebase-tools
      - name: Deploy to Firebase
        run: |
          ./node_modules/.bin/firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project codesupport-production
      - name: Notify Discord Channel
        run: |
          if [ "${{ github.event.head_commit.message }}" != "" ]; then
            curl -XPOST -H "Content-type: application/json" -d '{"embeds":[{"title":"Website Frontend Deployment","description":"The Website Frontend has successfully deployed.\n```${{ github.event.head_commit.message }}```","color":4627674,"author":{"name":"Firebase","icon_url":"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.NF8Usqcvj3UVmNtOmBfeMAD4D7%26pid%3DApi&f=1"}}],"username":"Firebase","avatar_url":"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.NF8Usqcvj3UVmNtOmBfeMAD4D7%26pid%3DApi&f=1"}' '${{ secrets.WEBHOOK_URL }}'
          fi
